name: CI

on:
  push:
    branches: [ "main", "sddf", "dev" ]

jobs:
  build:
    name: Build and upload SDK (Linux x86-64)
    # Don't want any forks or PRs to run this workflow
    if: ${{ github.repository_owner == 'Ivan-Velickovic' }}
    runs-on: self-hosted
    steps:
      - name: Checkout seL4 Core Platform repository
        uses: actions/checkout@v3
      - name: Checkout OpenSBI repository
        uses: actions/checkout@v3
        with:
            repository: riscv-software-src/opensbi
            ref: v1.0
            path: opensbi
      - name: Build SDK
        run: ./ci/build.sh
      - name: Test SDK
        run: ./pyenv/bin/python ./ci/test.py
      - name: Archive SDK
        uses: actions/upload-artifact@v3
        with:
            name: sel4cp-sdk-latest-${{ github.ref_name }}-linux-x86_64
            path: ./release/sel4cp-sdk-1.2.6.tar.gz
