name: Docker Example Builder Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sel4cp:latest
